### PR TITLE
Rework avatar to fix change-in-update warnings

### LINKED ISSUE #859: Bug in Avatar causing `change-in-update` Lit warning
When running unit tests:

```
packages/components/avatar/src/avatar.spec.ts:

 🚧 Browser logs:
      Element sl-avatar scheduled an update (generally because a property was set) after an update completed, causing a new update to be scheduled. This is inefficient and should be avoided unless the next update can only be scheduled as a side effect of the previous update. See https://lit.dev/msg/change-in-update for more information.
```

### PR DESCRIPTION
**Pull request by jpzwarte**
Fixes #859

### CODE REVIEW

**Review by Diaan — APPROVED** [review]

File: packages/components/avatar/src/avatar.ts [hunk 1]
```diff
@@ -194,12 +179,23 @@ export class Avatar extends LitElement {
   }
 
   #renderPicture(): TemplateResult {
-    const { x, y, containerSize, radius, size } = this.image!;
+    const { x, y, containerSize, radius, size } = this.image!,
+      parts: string[] = [];
```
Comment (Diaan) [inline packages/components/avatar/src/avatar.ts:183]: `parts` isn't a very clear name (i assume it was called this in a function/context that made the label, so it could be inferred from the context that it were label-parts, but that context is gone here.)
