### PR TITLE
Fix regression for drag and drop within grid

### LINKED ISSUE #2073: [grid] Fixes drag & drop regression for basic rows
### Provide a general summary of the issue here

Get the basic DnD behavior in grid working again

### 👤 Your name

Jeroen

### 🧢 Your Product/Team

SLDS

### PR DESCRIPTION
**Pull request by jpzwarte**
Fixes #2073

### CODE REVIEW

File: packages/components/grid/src/grid.ts [hunk 1]
```diff
@@ -687,34 +691,27 @@ export class Grid<T = any> extends ScopedElementsMixin(LitElement) {
...
-      row.style.removeProperty('--_cell-background');
-      row.style.removeProperty('border');
-      row.style.removeProperty('opacity');
-
       if (this.draggableRows !== 'between-or-on-top') {
         this.dropTargetMode = this.draggableRows;
       }
 
-      this.view.refresh();
+      // this.view.refresh();
```
Comment (Diaan) [inline packages/components/grid/src/grid.ts:711]: comment

File: packages/components/grid/src/grid.ts [hunk 2]
```diff
@@ -807,7 +807,7 @@ export class Grid<T = any> extends ScopedElementsMixin(LitElement) {
       this.draggableRows === 'between' ||
       (this.draggableRows === 'between-or-on-top' && this.dropTargetMode === 'between')
     ) {
-      const index = this.view.rows.indexOf(this.#dragItem!);
+      const index = 0; //this.view.rows.indexOf(this.#dragItem!);
```
Comment (Diaan) [inline packages/components/grid/src/grid.ts:810]: comment

File: packages/components/grid/src/grid.ts [hunk 3]
```diff
@@ -824,7 +824,7 @@ export class Grid<T = any> extends ScopedElementsMixin(LitElement) {
       });
 
       if (!cancelled) {
-        this.view.reorderItem(this.#dragItem!, relativeItem, index === 0 ? 'before' : 'after');
+        // this.view.reorderItem(this.#dragItem!, relativeItem, index === 0 ? 'before' : 'after');
```
Comment (Diaan) [inline packages/components/grid/src/grid.ts:827]: comment

**Review by Diaan — APPROVED** [review]
