### PR TITLE
fix(select): observe and update selected option content

### LINKED ISSUE #3239: [Select] Selected option content does not update when mutated in runtime
### 😯 Current Behavior

When an `sl-option`'s text or child content **is mutated** after it has **already been selected**, the closed `sl-select` button continues to show the stale label. 

In addition - the selected option content inside the dropdown **is updated**.

Image

### 🤔 Expected Behavior/possible solution?

Selected option content is always up-to-date with how it was mutated in runtime

### 🖥️ Steps to Reproduce

1. Select an option in an `sl-select`
2. Modify the selected option's content in runtime

### Were you able to reproduce this in our storybook?

Yes

### If yes, provide the storybook URL

_No response_

### If no, provide a code reproduction

_No response_

### ⚖️ Impact

This blocks our release or stops us from using this component

### Framework

Angular

### What browsers are you seeing the problem on?

Chrome

### If other, please specify.

_No response_

### What operating system are you using?

_No response_

### Component version

2.1.3

### Theme version

_No response_

### 👤 Your name

Bartosz Wasilew

### 🧢 Your product/team

_No response_

### 🎨 Your Theme(s)

Sanoma Learning

### PR DESCRIPTION
**Pull request by bartosz-wasilew-sl**
Fixes #3239

### CODE REVIEW

File: packages/components/select/src/select.ts [hunk 1]
```diff
@@ -236,6 +239,7 @@ export class Select<T = any> extends ObserveAttributesMixin(FormControlMixin(Sco
 
   override disconnectedCallback(): void {
     this.#observer.disconnect();
+    this.#selectedOptionObserver.disconnect();
```
Comment (michal-sanoma) [inline packages/components/select/src/select.ts:247]: **suggestion:** Nice fix overall. One edge case: we disconnect `#selectedOptionObserver` in `disconnectedCallback()`, but I don’t see it being re-attached on `connectedCallback()` when `selectedOption` is already set. 

If the component is detached and re-attached without changing `value`, runtime mutations of the selected option may stop updating the button content. Could we re-observe on connect and add a regression test for detach/attach?

File: packages/components/select/src/select.ts [hunk 2]
```diff
@@ -416,6 +420,16 @@ export class Select<T = any> extends ObserveAttributesMixin(FormControlMixin(Sco
...
   }
 
+  #onSelectedOptionContentChange(): void {
+    if (!this.selectedOption) {
+      return;
+    }
+
+    this.#lastRenderedOption = undefined;
+    this.#renderSelectedContent();
+    this.#calculateLargestOptionWidth();
```
Comment (michal-sanoma) [inline packages/components/select/src/select.ts]: **question:** Small performance question: `#onSelectedOptionContentChange()` recalculates largest option width on every mutation. For frequently changing content this could trigger repeated layout work. Would it make sense to batch/debounce this recalculation (e.g. microtask/rAF) or gate it more narrowly?

Comment (bartosz-wasilew-sl) [reply packages/components/select/src/select.ts]: That's a good one. Sure - performance-wise - it costs.

But I cannot imagine how it could work without re-calculating the largest width, when we (as per purpose of this feature) update content (that can be "very different" in terms of width, comparing to the one before an update). Example: runtime translations.

Do you see a scenario when the number of "needed re-calculations" is lower than "each time we change content"?

File: packages/components/select/src/select.ts (hunk 1 above)
Comment (bartosz-wasilew-sl) [reply packages/components/select/src/select.ts:247]: Thanks.

Indeed we disconnect the `#selectedOptionObserver` as we disconnect the whole `Select` - treat it as a cleanup.

And indeed we re-attach/re-connect, but only when the `selectedOption` is available (`#selectedOptionObserver`).

The `connectedCallback()` "hook" concerns the `Select` overall - and yet, at the component init - there's no `selectedOption` === nothing to observe yet.

Comment (michal-sanoma) [reply packages/components/select/src/select.ts:247]: Thanks for clarifying, I'm still new to Lit.js so maybe I'm missing sth but we may still be missing the re-subscribe path for the detach/attach case when `value` does not change.

From what I see, we disconnect in `disconnectedCallback()`, and `observe(...)` is only re-attached inside `#setSelectedOption(...)`. If the same selected option remains selected across re-attach, `#setSelectedOption(...)` may not run, so runtime mutations would no longer refresh selected content.

File: packages/components/select/src/select.ts (hunk 2 above)
Comment (michal-sanoma) [reply packages/components/select/src/select.ts]: Makes sense, and I agree we need width recalculation for correctness.

My concern is only about frequency, not removing recalculation: one logical content update can produce multiple MutationObserver records in the same tick (e.g. runtime i18n / framework patching several text nodes). In that case we currently run full width measurement multiple times, even though one final measurement would be enough

File: packages/components/select/src/select.ts [hunk 3]
```diff
@@ -416,6 +420,16 @@ export class Select<T = any> extends ObserveAttributesMixin(FormControlMixin(Sco
...
+  }
```
[the remark this answers is not in the document]
Comment (michal-sanoma) [reply packages/components/select/src/select.ts]: fixed

File: packages/components/select/src/select.ts (hunk 1 above)
Comment (michal-sanoma) [reply packages/components/select/src/select.ts:247]: fixed here https://github.com/sl-design-system/components/pull/3240/changes/42384a4b9d064edcdebf8d5bd76cfeadc92045c7

File: packages/components/select/src/select.ts (hunk 2 above)
Comment (michal-sanoma) [reply packages/components/select/src/select.ts]: fixed here: https://github.com/sl-design-system/components/pull/3240/changes/42384a4b9d064edcdebf8d5bd76cfeadc92045c7

File: packages/components/select/src/select.ts [hunk 4]
```diff
@@ -721,6 +750,31 @@ export class Select<T = any> extends ObserveAttributesMixin(FormControlMixin(Sco
...
+    this.#selectedOptionObserver.disconnect();
+
+    if (!this.selectedOption) {
+      return;
+    }
+
+    this.#selectedOptionObserver.observe(this.selectedOption, {
+      childList: true,
+      subtree: true,
+      characterData: true
```
[the remark this answers is not in the document]
Comment (michal-sanoma) [reply packages/components/select/src/select.ts]: fixed

File: packages/components/select/src/select.ts [hunk 5]
```diff
@@ -229,13 +235,19 @@ export class Select<T = any> extends ObserveAttributesMixin(FormControlMixin(Sco
     this.setAttributesTarget(this.button);
 
     this.#observer.observe(this, { childList: true, subtree: true });
+    this.#observeSelectedOptionContent();
```
[the remark this answers is not in the document]
Comment (michal-sanoma) [reply packages/components/select/src/select.ts:240]: fixed

File: packages/components/select/src/select.ts [hunk 6]
```diff
@@ -416,6 +429,22 @@ export class Select<T = any> extends ObserveAttributesMixin(FormControlMixin(Sco
...
+
+    const selectedOptionValue = this.selectedOption.value;
+    if (selectedOptionValue !== this.value) {
+      this.value = selectedOptionValue;
+      this.#updateValueAndValidity();
+    }
+
+    this.#lastRenderedOption = undefined;
+    this.#renderSelectedContent();
+    this.#scheduleLargestOptionWidthCalculation();
```
Comment (Diaan) [inline packages/components/select/src/select.ts:451]: does it need this? The list of options doesn't change here, right? Why do we need to recalculate the width?

**Review by Diaan — APPROVED** [review]

File: packages/components/select/src/select.ts (hunk 6 above)
Comment (michal-sanoma) [reply packages/components/select/src/select.ts:451]: true, I've added an early return
