### PR TITLE
Log a warning when you use `<sl-select>` without having `<sl-option>` registered

### LINKED ISSUE #1894: [SELECT][LISTBOX] Select requires listbox dependency to work
### Provide a general summary of the issue here

Select options are broken when @sl-design-system/listbox is not installed

### 🤔 Expected Behavior?

@sl-design-system/select should either:
- work standalone without listbox
- throw error during npm install that it requires listbox

It would be nice to mentiont that within the documentation

### 😯 Current Behavior

When you open a select options error is thrown within the console and you can see that something is wrong.

### 💁 Possible Solution

_No response_

### 🖥️ Steps to Reproduce

1. Checkout on angular-demo main
2. remove  "@sl-design-system/listbox" "^0.1.0"
3. add schemas: [CUSTOM_ELEMENTS_SCHEMA], to form.component.ts

Image

### What browsers are you seeing the problem on? (only for bugs in code)

Chrome

### If other, please specify.

_No response_

### What operating system are you using?

Windows

### 👤 Your name

Jakub Wachowiak

### 🧢 Your product/team

ETSL

### 🎨 Your Theme(s)

Editorial Suite

### PR DESCRIPTION
**Pull request by jpzwarte**
Fixed #1894

### CODE REVIEW

**Review by anna-lach — APPROVED** [review]

File: packages/components/select/src/select.ts [hunk 1]
```diff
@@ -481,4 +483,14 @@ export class Select<T = any> extends ObserveAttributesMixin(FormControlMixin(Sco
 
     this.updateValidity();
   }
+
+  #verifyRegisteredListboxElements(): void {
+    const option = this.querySelector('sl-option');
+
+    if (option && !(option instanceof Option)) {
```
Comment (Diaan) [inline packages/components/select/src/select.ts:490]: We have more components where we send warnings if the dev is doing something wrong/is missing something, but we only send those when in dev mode. Is that something we want here as well?

**Review by Diaan — APPROVED** [review]

File: packages/components/select/src/select.ts (hunk 1 above)
Comment (jpzwarte) [reply packages/components/select/src/select.ts:490]: I think in this case it is fine to have it in production as well. It is something that really should be fixed, even in production.
