### PR TITLE
fix(number-field): preserve external custom validity messages on reportValidity

### LINKED ISSUE #3140: [Form, NumberField] - Custom validity message it's not displaying it
### Provide a general summary of the issue here

When i call `setCustomValidity('Hello world')` on `<sl-text-field>`, it displays the message; on `<sl-number-field>`, it doesn't

### 🤔 Expected Behavior?

It should show the message the same way it does in `sl-text-field`

### 😯 Current Behavior

It's not showing the custom message in `sl-number-field`

### 💁 Possible Solution

_No response_

### 🖥️ Steps to Reproduce

```
onInputChange(event: CustomEvent) {
    const target = event.target as HTMLElement & FormControl;
    const message =
      target.getAttribute('data-validation-message') || 'Invalid input';
    target.setCustomValidity(message);
    target.reportValidity();
  }

  override render() {
    return html`
      <sl-form class="section-number-selector-container">
        <sl-form-field>
          <sl-label size="md">Number of sections: </sl-label>
          <sl-number-field
            required
            id="sections-number-input${this.index}"
            input-size="8"
            data-validation-message="Paragraph can not be empty."
            valueAsNumber=${this.value}
            min="2"
            max="10"
            @sl-blur=${this.onInputChange}
          ></sl-number-field>
        </sl-form-field>
      </sl-form>
    `;
  }
}
```

### What browsers are you seeing the problem on? (only for bugs in code)

Chrome

### If other, please specify.

_No response_

### What operating system are you using?

Windows 11

### 👤 Your name

Oscar Ledesma

### 🧢 Your product/team

BingelDC/Pokemon

### 🎨 Your Theme(s)

Bingel DC

### PR DESCRIPTION
**Pull request by michal-sanoma**
## Summary

This PR fixes a validation regression in `sl-number-field` where externally set custom validity messages were cleared during reportValidity()

https://github.com/user-attachments/assets/2d2b0b0f-9bb6-422e-81ae-00fedd86e41f

### CODE REVIEW

File: packages/components/number-field/src/number-field.ts [hunk 1]
```diff
@@ -287,27 +293,51 @@ export class NumberField extends LocaleMixin(TextField) {
...
-      this.setCustomValidity('');
+      this.#setInternalCustomValidity('');
     }
   }
 
+  #setInternalCustomValidity(message: string): void {
+    this.#settingInternalCustomValidity = true;
+    this.#internalCustomValidity = message;
+    this.setCustomValidity(message);
+    this.#settingInternalCustomValidity = false;
```
[the remark this answers is not in the document]
Comment (michal-sanoma) [reply packages/components/number-field/src/number-field.ts]: added

File: .changeset/late-knives-notice.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'@sl-design-system/number-field': patch
+---
+
+Fix `sl-number-field` so custom validity messages set externally via `setCustomValidity(...)` are preserved when `reportValidity()` runs. This prevents internal validity updates from clearing user-defined errors. Also adds a regression test for this behavior
```
[the remark this answers is not in the document]
Comment (michal-sanoma) [reply .changeset/late-knives-notice.md]: added

File: .changeset/late-knives-notice.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
+---
+'@sl-design-system/number-field': patch
+---
+
+Fix `sl-number-field` so custom validity messages set externally via `setCustomValidity(...)` are preserved when `reportValidity()` runs. This prevents internal validity updates from clearing user-defined errors. Also adds a regression test for this behavior.
```
Comment (anna-lach) [inline .changeset/late-knives-notice.md:5]: Could you please add a story with custom validity, maybe similar to this one? https://storybook.sanomalearning.design/?path=/story/form-text-field--custom-validity

File: packages/components/number-field/src/number-field.ts [hunk 4]
```diff
@@ -302,32 +308,52 @@ export class NumberField extends LocaleMixin(TextField) {
...
+    if (!this.#settingInternalCustomValidity) {
+      this.#internalCustomValidity = '';
+    }
+
+    super.setCustomValidity(message);
+  }
+
   /** @internal Implement custom number validity checks. */
   override updateInternalValidity(): void {
+    const hasExternalCustomError = this.validity.customError && this.validationMessage !== this.#internalCustomValidity;
```
Comment (anna-lach) [inline packages/components/number-field/src/number-field.ts]: Maybe we can use just a simpler solution like in the time-field?

Image

File: .changeset/late-knives-notice.md (hunk 3 above)
Comment (michal-sanoma) [reply .changeset/late-knives-notice.md:5]: sure, added

File: packages/components/number-field/src/number-field.ts (hunk 4 above)
Comment (michal-sanoma) [reply packages/components/number-field/src/number-field.ts]: simplified

**Review by anna-lach — APPROVED** [review]

File: packages/components/number-field/src/number-field.ts [hunk 5]
```diff
@@ -321,16 +334,21 @@ export class NumberField extends LocaleMixin(TextField) {
...
       );
     } else {
-      this.setCustomValidity('');
+      this.#setInternalCustomValidity('');
     }
   }
 
+  #setInternalCustomValidity(message: string): void {
+    this.#hasInternalCustomError = message !== '';
+    super.setCustomValidity(message);
```
[the remark this answers is not in the document]
Comment (michal-sanoma) [reply packages/components/number-field/src/number-field.ts:349]: edge-case
